import javax.swing.JOptionPane;

/**
 *
 * @author gummlas
 */
public class ContohSwingRadioButtonFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form ContohSwingRadioButtonFrame1
     */
    public ContohSwingRadioButtonFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jenisKelaminButtonGroup = new javax.swing.ButtonGroup();
        statusPerkawinanButtonGroup = new javax.swing.ButtonGroup();
        golonganDarahButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        belumKawinRadioButton = new javax.swing.JRadioButton();
        kawinRadioButton = new javax.swing.JRadioButton();
        dudaJandaRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        aRadioButton = new javax.swing.JRadioButton();
        bRadioButton = new javax.swing.JRadioButton();
        aBRadioButton = new javax.swing.JRadioButton();
        oRadioButton = new javax.swing.JRadioButton();
        resetButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contoh Swing Radio Button");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Contoh Swing Radio Button");

        jLabel2.setText("Jenis Kelamin");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jenisKelaminButtonGroup.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setText("Laki-laki");
        lakiLakiRadioButton.setActionCommand("L");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        jenisKelaminButtonGroup.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.setActionCommand("P");

        jLabel3.setText("Status Perkawinan");

        statusPerkawinanButtonGroup.add(belumKawinRadioButton);
        belumKawinRadioButton.setSelected(true);
        belumKawinRadioButton.setText("Belum Kawin");
        belumKawinRadioButton.setActionCommand("Belum Kawin");

        statusPerkawinanButtonGroup.add(kawinRadioButton);
        kawinRadioButton.setText("Kawin");
        kawinRadioButton.setActionCommand("Kawin");

        statusPerkawinanButtonGroup.add(dudaJandaRadioButton);
        dudaJandaRadioButton.setText("Duda/Janda");
        dudaJandaRadioButton.setActionCommand("Duda/Janda");

        jLabel4.setText("Golongan Darah");

        golonganDarahButtonGroup.add(aRadioButton);
        aRadioButton.setText("A");
        aRadioButton.setActionCommand("A");

        golonganDarahButtonGroup.add(bRadioButton);
        bRadioButton.setText("B");
        bRadioButton.setActionCommand("B");

        golonganDarahButtonGroup.add(aBRadioButton);
        aBRadioButton.setText("AB");
        aBRadioButton.setActionCommand("AB");
        aBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBRadioButtonActionPerformed(evt);
            }
        });

        golonganDarahButtonGroup.add(oRadioButton);
        oRadioButton.setText("O");
        oRadioButton.setActionCommand("O");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(bRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(aBRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(oRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(belumKawinRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kawinRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dudaJandaRadioButton)))))
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                    .addComponent(lakiLakiRadioButton)
                                    .addGap(34, 34, 34)
                                    .addComponent(perempuanRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(belumKawinRadioButton)
                    .addComponent(kawinRadioButton)
                    .addComponent(dudaJandaRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aRadioButton)
                    .addComponent(bRadioButton)
                    .addComponent(aBRadioButton)
                    .addComponent(oRadioButton))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton)
                    .addComponent(exitButton))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        if(jenisKelaminButtonGroup.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Silakan pilih Jenis Kelamin", "Pesan Error!", JOptionPane.ERROR_MESSAGE);
        }else if(golonganDarahButtonGroup.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Silakan pilih Golongan Darah", "Pesan Error!", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Jenis Kelamin: "+jenisKelaminButtonGroup.getSelection().getActionCommand() +
                    "\nStatus Perkawinan: "+statusPerkawinanButtonGroup.getSelection().getActionCommand() +
                    "\nGolongan Darah: "+golonganDarahButtonGroup.getSelection().getActionCommand(),
                    "Hasil pilihan Radio Button", JOptionPane.INFORMATION_MESSAGE);

        }
    }                                            

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void aBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        jenisKelaminButtonGroup.clearSelection();
        belumKawinRadioButton.setSelected(true);
        golonganDarahButtonGroup.clearSelection();
    }                                           

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        System.exit(0);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContohSwingRadioButtonFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContohSwingRadioButtonFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContohSwingRadioButtonFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContohSwingRadioButtonFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContohSwingRadioButtonFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton aBRadioButton;
    private javax.swing.JRadioButton aRadioButton;
    private javax.swing.JRadioButton bRadioButton;
    private javax.swing.JRadioButton belumKawinRadioButton;
    private javax.swing.JRadioButton dudaJandaRadioButton;
    private javax.swing.JButton exitButton;
    private javax.swing.ButtonGroup golonganDarahButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup jenisKelaminButtonGroup;
    private javax.swing.JRadioButton kawinRadioButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JRadioButton oRadioButton;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JButton resetButton;
    private javax.swing.ButtonGroup statusPerkawinanButtonGroup;
    private javax.swing.JButton submitButton;
    // End of variables declaration                   
}

